### ISSUE TITLE
I can't believe you did it ！

### ISSUE THREAD

**Issue by FangSen9000** [reallyigor/easy_dwpose#1]
Are you saying that you implemented a method in this project to save all the key points of dwpose, like json of openpose？

**Comment by reallyigor** [comment]
yea, you can easily access an array of keypoints
but it's a python dict, not in a json format, you would need to convert it to json yourself
Feel free to describe why do you need a .json, and i'll implement it

**Comment by FangSen9000** [comment]
> yea, you can easily access an array of keypoints but it's a python dict, not in a json format, you would need to convert it to json yourself Feel free to describe why do you need a .json, and i'll implement it

It doesn't matter if it's a dictionary or something, as long as the posture information can be stored. There has been a lot of work over the last five or six years based on openpose's json file, and it would be helpful for researchers to store this information. 

This will make the repository even more popular, some models, when they read, they read json by default. Of course, a dictionary is fine, as long as you can output it to a file.
